spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sda_gift?useSSL=false
        username: root
        password: j987jklm
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        druid:
          min-idle:
server:
  port: 8090
