spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sda_gift?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true"
        username: root
        password: j987jklm
        driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8090
