gift:
    activityName: "中秋节"
    quota: 1000
    pigId: "e08b8190684f438db922580bc42a7d8f"

spring:
  profiles:
    active: "pro"
logging:
  file: gift.log
  level:
    org:
      mybatis: TRACE
      springframework: INFO
      com.sda.gift: TRACE
      com.sda.gift.mapper: DEBUG
