spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sda_gift?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: j987jklm
        driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8090
