spring:
    datasource:
        name: test
        url: jdbc:mysql://local:3306/discount_ticket_system
        username: root
        password: j987jklm
        driver-class-name: com.mysql.jdbc.Driver